apiVersion: apps/v1
kind: Deployment
metadata:
  name: udp-demo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      bb: udp-demo
  template:
    metadata:
      labels:
        bb: udp-demo
    spec:
      hostNetwork: true
      containers:
      - name: udp-demo
        image: localhost:5000/config:1
        env:
        - name: T_PORT
          value: "6701"
        - name: T_IP
          value: "239.0.0.0"
        - name: T_HOST
          value: "239.0.0.0"
        - name: T_FLAG_SEND
          value: "true"
          
